notifications:
  email: false
language: python
python:
  - "3.9"
  - "3.10"
  - "3.11"
sudo: required
dist: focal

# Install dependencies
before_install:
- pip install poetry
install:
- poetry install -v

# Run tests
script: pytest
