notifications:
  email: false
language: python
python:
  - "3.8"
  - "3.9"

sudo: required
dist: focal

# Install dependencies
before_install:
- pip install poetry
install:
- poetry install -v

# Run tests
script: pytest
